### ISSUE TITLE
Problem (and solution) to compile on Ubuntu 21.10 and Ubuntu 22.04

### ISSUE THREAD

**Issue by vtamara** [ton-blockchain/ton#339]
During the compilation it produces:

```
[ 55%] Linking CXX static library librocksdb.a                                 
[ 55%] Built target rocksdb                                                    
make[1]: *** [CMakeFiles/Makefile2:8018: crypto/CMakeFiles/fift.dir/rule] Error 2
```

**Comment by vtamara** [comment]
After the error running:
```
cd /usr/bin/ton/
sudo make -j 2 fift
```
produces
```
/usr/src/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:26: error: no member named 'numeric_limits' in namespace 'std'             
  if (x->version == std::numeric_limits<uint32_t>::max()) {                                                                                                     
                    ~~~~~^                                                                                                                                      
/usr/src/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:41: error: unexpected type name 'uint32_t': expected expression            
  if (x->version == std::numeric_limits<uint32_t>::max()) {                     
                                        ^                                       
/usr/src/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:52: error: no member named 'max' in the global namespace                   
  if (x->version == std::numeric_limits<uint32_t>::max()) {                                                                                                     
```

**Comment by vtamara** [comment]
However updating to the latest version of `abseil-cpp` solves the problem:
```
cd /usr/src/ton/third-party/abseil-cpp
sudo git checkout master
sudo git pull
cd /usr/bin/ton
sudo rm -rf *
sudo cmake -DCMAKE_BUILD_TYPE=Release /usr/src/ton/
sudo make -j 2 fift validator-engine lite-client pow-miner validator-engine-console generate-random-id dht-server
```
